language: node_js
node_js:
- 14.21.3
install:
- npm ci
- HUSKY_SKIP_INSTALL=1 npm i --no-save react react-dom react-router-dom react-helmet-async
  @apollo/client@^3.0.0 graphql@^15.0.0 html-webpack-plugin@^5.0.0 subscriptions-transport-ws@^0.9.0
deploy:
  provider: npm
  skip_cleanup: true
  email: jonny@jondarrer.me.uk
  on:
    tags: true
  api_key:
    secure: z4SYLczSENeYf6o/psuJU7l0MWDmh/SQHbUP7zjgMOppfIs5vw6GFrvHocEotjxsqCCsrX4TCN593TdckUAee7trdz69i3sWsme7LZBeCJUHJVeABDzNiwfPJyPrM8r85wvMxcCyVeE127NIUZPIR5fshE6BfhHvWBBQ/6GQ2thnUvlZso7UufvarekjlXMpl4p/LOKfPpCk8d1kHumJFgeGE1JHcHXaJjGD3ifjiqH0sZz7Ya0Ba+VB0WMzO2IPWCWV8byjiIculS4iyCqyXukFgM/T4bb2sc0W2LhS/WaX9HbUkkKYlqIcVEKtZWE1awKLuA1cpMlf08npKXPT6yg0MjHxkJe5Lr8+Eyu0I1SRB63BqQN9sseNx8WPwbMiaAsGDyyknZ5xxlPvvrW9Mt/ZU4DIAgmnY9/g/16Xfq4g9hBF77nUrqYFG0sY2Y/UZrwjzdmhf/2J66GVohxqofH07SBDz7JL7HzThQsHieqU2e7g8SXr2cYdU0kI/yXQCkcUZ5MXZt3qUdYqDFP+UNLqnxZ+LtAsQI+K2S8mav87yjECSjpEvTri9niRevEDF3RZaxVdnJUeY2mfdH/ScIzrzrVAvAYDFhH5fn7q1T5+8wFP9z+bZRQPZ9N7Iw3zZOoIZMrJF3oikjx7RhapDWL6jC7SHzIrfaehLmlKxas=
