language: node_js
node_js:
- 12.14.1
deploy:
  provider: npm
  email: jonny@jondarrer.me.uk
  api_key:
    secure: WaJi6I40Sl3AkGanwnyBf+cqziLxW/SJkjFGq1mp0s9udw9vflBGx12ve/onEqJRcJsjlaA50lNihV7mQf0lYgfYtSYIeTqEzASK5i79soBlfZvn1ZoHIRkKBq7nXzD6v2AKI6s17gUaDe80WMaxejGKlhW89U7xGEEHcmkAkrmcbM9gom7ZAVZHkz3SGjj/AOo+rnWJgFQcS9X1EqUQBmn+lzOahIom4W6+fDSs86lgocFUkvAZQHKkRAwaNdRSbyyjvi5Lo9/T4haj3CuKEUEaQUY4g2avk8ocmnKqCl9kodIyXJlOGQjDVphlDWOIch2uJDLlAUQ1Z+TL+rqRWs9g63ECVA4CjEkssnNyaRxAEo3XwPokNRnplB+CxOhKV9gxYGORansgSULsrbkIeMYriqKjZwAansOnx2fiTxsTF6HsafEQCRiKqW1BNqomv+vReK/i4zqSN3a4uogL6oM6fBTlTyeXtFGWrFN/LU6QYpYdkMYXIOML3oeDtitkEOztSxUtAhnu/YZI1RPxSjnjCx4JDFOyaYVqnJdEL6ckd3XFeOVa32KyQIblLZ+PSamKJV5lI/X7+PMrLEqAsRpq2rURIMIruXaqCHIdb/fAP96xU+SQLXcwIGOFOg9QVmDikEcnTGC8Xf0bBTwC0W3PnsLydZYAlI0MzBZ6MBs=
